#
# Module manifest for module 'ProfilePal'
# Generated by: Bryan Dady; http://bryan.dady.us
# Generated on: 3/10/2015

@{
# Script module or binary module file associated with this manifest.
RootModule = 'ProfilePal.psm1'

# Version number of this module.
ModuleVersion = '1.3'

# ID used to uniquely identify this module
GUID = 'c2e2d90b-42f5-417d-935d-e2d1d4e734ea'

# Author of this module
Author = 'Bryan Dady'

# Company or vendor of this module
CompanyName = 'GBCI'

# Copyright statement for this module
Copyright = '(c) 2015 Bryan Dady. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module library of commonly used functions, especially useful for frequent re-use in PowerShell profiles'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# HelpInfo URI of this module
# HelpInfoURI = ''

}

