#
# Module manifest for module 'ProfilePal'
#
# Generated by: Bryan Dady; http://bryan.dady.us
#
# Generated on: 6/13/2016
#
# Update 1.1.0:  7/14/2017, Replace explicit PowerShell_ISE.exe dependency with support for VS Code (reliant on Open-PSEdit to define preferred editor)
# Update 1.1.1: 11/16/2017, Renamed -WindowTitle functions to -ConsolTitle, to improve Get- tab completion
# Update 1.1.2: 02/21/2018, Fixed errant .WindowTitle property reference introduced in 1.1.1; Improved for and tested on PowerShell Core (6.0.1)

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProfilePal.psm1'

# Version number of this module.
ModuleVersion = '1.1.2'

# ID used to uniquely identify this module
GUID = 'c2e2d90b-42f5-417d-935d-e2d1d4e734ea'

# Author of this module
Author = 'Bryan Dady'

# Copyright statement for this module
Copyright = '(c) 2015 Bryan Dady. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module library of commonly used functions, especially useful for frequent re-use in PowerShell profiles'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Functions to export from this module
FunctionsToExport = @('Add-EnvPath','Assert-PSEdit','Edit-Profile','Get-ConsoleTitle','Get-EnvPath','Get-EnvPathFromRegistry','Get-Profile','Get-PSEdit','Get-UserName','New-Profile','Open-AdminConsole','Open-AdminEditor','Open-PSEdit','prompt','Remove-EnvPath','Repair-EnvPath','Reset-ConsoleTitle','Reset-Profile','Resume-Profile','Set-ConsoleTitle','Set-EnvPath','Start-RemoteDesktop','Suspend-Profile','Test-EnvPath','Test-FileTypeAssociation','Test-LocalAdmin','Test-Port','Test-UserFileType','Test-UserProgID')

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('Initialize-Profile', 'New-AdminConsole', 'New-AdminHost', 'Open-AdminHost', 'rdp', 'Start-AdminConsole', 'Start-AdminHost', 'sudo', 'telnet', 'Update-ConsoleTitle', 'whoami')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('AdminConsole.ps1', 'ProfilePal.psm1', 'toolbox.ps1')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @('PSModule', 'Profile', 'LocalAdmin')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/bcdady/ProfilePal/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Update 1.1.2: 02/21/2018, Fixed errant .WindowTitle property reference introduced in 1.1.1;Improved for and tested on PowerShell Core (6.0.1)'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

