#
# Module manifest for module 'ProfilePal'
#
# Generated by: Bryan Dady
#
# Generated on: 6/13/2016
#
# Update 1.0.8:  6/20/2017, Remove unused Show-MsgBox.ps1
# Update 1.1.0:  7/14/2017, Replace explicit PowerShell_ISE.exe dependency with support for VS Code (reliant on Open-PSEdit to define preferred editor)

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProfilePal.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# ID used to uniquely identify this module
GUID = 'c2e2d90b-42f5-417d-935d-e2d1d4e734ea'

# Author of this module
Author = 'Bryan Dady'

# Company or vendor of this module
#CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015 Bryan Dady. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module library of commonly used functions, especially useful for frequent re-use in PowerShell profiles'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('AdminConsole.ps1', 'toolbox.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Edit-Profile', 'Get-Profile', 'Get-UserName', 'Get-WindowTitle', 'Test-LocalAdmin', 'New-Profile', 'Open-AdminConsole', 'prompt', 'Reset-Profile', 'Reset-WindowTitle', 'Resume-Profile', 'Set-WindowTitle', 'Start-RemoteDesktop', 'Suspend-Profile', 'Test-Port')

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('Initialize-Profile', 'New-AdminConsole', 'New-AdminHost', 'Open-AdminHost', 'rdp', 'Start-AdminConsole', 'Start-AdminHost', 'sudo', 'telnet', 'Update-WindowTitle', 'whoami')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('AdminConsole.ps1', 'ProfilePal.psm1', 'toolbox.ps1')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @('PSModule', 'Profile', 'LocalAdmin')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/bcdady/ProfilePal/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Update 1.0.8:  6/20/2017, Remove unused Show-MsgBox.ps1.'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

